
# <center>Soil-based Plant Recommendations</center>

#### Tentang Notebook
Dalam notebook ini, dilakukan data processing dengan mengidentifikasi anomali dari data (null value, outlier, dll). Kemudian akan dihasilkan statistik dan visualiasi untuk tahap EDA.

### Import packages

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
import seaborn as sb
%matplotlib inline

## Read Data

In [2]:
df1 = pd.read_csv("../data-raw/Crop_recommendation.csv")

df1.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
df2 = pd.read_csv("../data-raw/crops.csv")

df2.head()

,Crop,ScientificName,Symbol,NuContAvailable,PlantPartHarvested,CropCategory,YieldUnit,AvYieldUnitWeight(lb),AvMoisture%,AvN%(dry),...,N%(wet)_M-FF,P%(wet)_M-FF,gP/100g(wet)_AgH8-9,gP/100g(wet)_AgH8-12,gP/100g(wet)_B788,P%(wet)_M&L,K%(wet)_M-FF,gK/100g(wet)_AgH8-9,gK/100g(wet)_AgH8-12,gK/100g(wet)_B788
0,Acorn,Quercus sp.,QUERC,"N,P,K",Fruit,Tree and fruit,lb of fruit,1.0,27.90,1.3647711512,...,NaN,NaN,NaN,0.079,NaN,NaN,NaN,NaN,0.539,NaN
1,"Alfalfa + Orchardgrass, for hay","Medicago sativa, Dactylis glomerata","MESA, DAGL","N,P",Aboveground biomass,Forage,ton,2000.0,9.70,2.4797142857,...,1.92,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Alfalfa + Orchardgrass, for hay (cut 1)","Medicago sativa, Dactylis glomerata","MESA, DAGL","N,P,K",Aboveground biomass,Forage,ton,2000.0,7.95,2.144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Alfalfa + Smooth Brome, for green chop","Medicago sativa, Bromus inermis","MESA, BRIN2","N,P,K",Aboveground biomass,Forage,ton,2000.0,77.63,3.3220740741,...,0.77,0.07,NaN,NaN,NaN,NaN,0.63,NaN,NaN,NaN
4,"Alfalfa + Smooth Brome, for hay","Medicago sativa, Bromus inermis","MESA, BRIN2","N,P,K",Aboveground biomass,Forage,ton,2000.0,11.58,2.4177085202,...,1.89,0.20,NaN,NaN,NaN,NaN,1.66,NaN,NaN,NaN